version: "3"
services:
  app:
    build: .
    volumes:
      - ./app:/app
    working_dir: /app
    links:
      - postgres
    env_file: .env
    ports:
      - 3000:3000
    command: npm run start
    
  postgres:
    image: "postgres:9.6.15"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
